set -e

nohup pulsar2 build --input flow_encoder_28.onnx --config config_flow_encoder_28.json --output_dir build-output-flow_encoder_28-0825 --output_name flow_encoder_28.axmodel --target_hardware AX650 --compiler.check  3 --compiler.check_cosine_simularity 0.98 > build_flow_encoder_28.log & #--debug.disable_auto_set_extremum_op_fp32 true
nohup pulsar2 build --input flow_encoder_53.onnx --config config_flow_encoder_53.json --output_dir build-output-flow_encoder_53-0825 --output_name flow_encoder_53.axmodel --target_hardware AX650 --compiler.check  3 --compiler.check_cosine_simularity 0.98 > build_flow_encoder_53.log & #--debug.disable_auto_set_extremum_op_fp32 true
nohup pulsar2 build --input flow_encoder_78.onnx --config config_flow_encoder_78.json --output_dir build-output-flow_encoder_78-0825 --output_name flow_encoder_78.axmodel --target_hardware AX650 --compiler.check  3 --compiler.check_cosine_simularity 0.98 > build_flow_encoder_78.log & #--debug.disable_auto_set_extremum_op_fp32 true
nohup pulsar2 build --input flow_encoder_50_final.onnx --config config_flow_encoder_50_final.json --output_dir build-output-flow_encoder_50_final-0825 --output_name flow_encoder_50_final.axmodel --target_hardware AX650 --compiler.check  3 --compiler.check_cosine_simularity 0.98 > build_flow_encoder_50_final.log & #--debug.disable_auto_set_extremum_op_fp32 true

nohup pulsar2 build --input flow_estimator_200.onnx --config config_flow_estimator_200.json --output_dir build-output-estimator-200 --output_name flow_estimator_200.axmodel --target_hardware AX650 --compiler.check  3 --compiler.check_cosine_simularity 0.98 >  build_estimator_200.log &
nohup pulsar2 build --input flow_estimator_250.onnx --config config_flow_estimator_250.json --output_dir build-output-estimator-250 --output_name flow_estimator_250.axmodel --target_hardware AX650 --compiler.check  3 --compiler.check_cosine_simularity 0.98 >  build_estimator_250.log &
nohup pulsar2 build --input flow_estimator_300.onnx --config config_flow_estimator_300.json --output_dir build-output-estimator-300 --output_name flow_estimator_300.axmodel --target_hardware AX650 --compiler.check  3 --compiler.check_cosine_simularity 0.98 >  build_estimator_300.log &